[package]
name = "theduke/wasmer-astro-starter1"
version = "0.2.4"
description = "Astro.dev Wasmer starter package"
readme = "README.md"
repository = "https://github.com/theduke/wasmer-astro-starter1"

[dependencies]
"wasmer/static-web-server" = "*"

[fs]
public = "dist"
